apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: ghcr-push-with-actions
  name: ghcr-push-with-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: ghcr-push-with-actions
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: ghcr-push-with-actions
    spec:
      containers:
        - image: ghcr.io/ber01/ghcr-push-with-actions:1.0.0
          imagePullPolicy: Always
          name: main
---
apiVersion: v1
kind: Service
metadata:
  name: ghcr-push-with-actions
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: ghcr-push-with-actions
